site_to_predict/app_to_predict/urls.py
from django.urls import path
from . import views

app_name = 'app_to_predict'

urlpatterns = [
    path('showall/', views.showall, name='showall'),
    path('upload/', views.upload, name='upload'),
]

site_to_predict/site_to_predict/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('app_to_predict/', include('app_to_predict.urls')),
    path('admin/', admin.site.urls),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site_to_predict/app_to_predict/models.py
from django.db import models

def get_image_path(self, filename):
    path = 'images/'
    name = "tmp.png"
    return path + name

class Image(models.Model):
    picture = models.ImageField(upload_to=get_image_path)

    def __str__(self):
        return self.title

site_to_predict/app_to_predict/forms.py
from django import forms
from .models import Image

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['picture']

site_to_predict/app_to_predict/views.py
import os
from django.shortcuts import render, redirect
from .models import Image
from .forms import ImageForm
from .deep_learning.train_neuralnet import neural
from django.conf import settings

def showall(request):
    images = Image.objects.all()
    result = neural()
    context = {'images':images, 'result':result}
    return render(request, 'app_to_predict/showall.html', context)

def upload(request):
    if request.method == "POST":
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            Image.objects.all().delete()
            if os.path.exists(settings.IMAGE_URL):
                os.remove(settings.IMAGE_URL)
            form.save()
            return redirect('app_to_predict:showall')
    else:
        form = ImageForm()

    context = {'form':form}
    return render(request, 'app_to_predict/upload.html', context)

site_to_predict/templates/app_to_predict/showall.html
{% load static %}
<!DOCTYPE html>
<head>
    <title>predict-handwriting-number</title>
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="stylesheet" type="text/css" href="{% static 'app_to_predict/style.css' %}">
</head>

<h2>Your Picture</h2>

{% for image in images %}
    <img src='{{ MEDIA_URL }}{{image.picture}}' width=200>

{% endfor %}
<h2>The handwriting number is maybe</h2>
<h1>[ {{ result }} ]</h1>
<h2><a href="{% url 'app_to_predict:upload' %}">Upload more</a></h2>

site_to_predict/templates/app_to_predict/upload.html
{% load static %}
<!DOCTYPE html>
<head>
    <title>predict-handwriting-number</title>
    <meta http-equiv="Cache-Control" content="no-cache">
    <link rel="stylesheet" type="text/css" href="{% static 'app_to_predict/style.css' %}">
</head>

<h1>Please Upload</h1>

<form enctype="multipart/form-data" action="{% url 'app_to_predict:upload' %}" method="post">
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="Upload">
</form>